# This is a basic workflow to help you get started with Actions

name: CI

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/users/RK-CDS/projects/2'
